export const ActionTypes={
    GET_LIST_POKEMON:"GET_LIST_POKEMON",
    GET_LIST_MY_POKEMON:"GET_LIST_MY_POKEMON",
    IMAGE_POKEMON:"IMAGE_POKEMON",
    DETAIL_POKEMON:"DETAIL_POKEMON",
    CATCH_POKEMON:"CATCH_POKEMON",
}